[credentials]
api_key = "ResyAPI api_key=\"VbWk7s3L4KiK5fzlO7JD3Q5EYolJI7n5\""  # Public API key, same for all users! Leave as is.

# Set username and password to false (bool) if you wish to enter manually on each run for better security.
# This is primarily here to speed up testing and isn't advised to be used.
user_name = false
password = false

[reservation_details]
# If manual input is desired for each run, replease one or all values with false.

# The size of your party, do not place quotes around this numerical value.
party_size = 2  # Type: integer | bool

# Military time only formatted as HH:MM:SS
# If no times are showing it's suggested to keep times in 15 min increments from the top of the hour as a general rule.
military_booking_time = "17:00:00"  # Type: str | bool

# Desired date of dining formatted only as YYYY-MM-DD, please keep within quotations.
date = "2025-01-25"  # Type: str

# Values can be found under times on the venue URL landing page. May or may not work.
# LEAVE THIS AS DINING ROOM EVEN IF YOU WISH TO USE MANUAL INPUT ON EACH RUN. DINING ROOM IS DEFAULT ON MANY PAGES.
desired_seating = "Dining Room"  # Type: str

# This is simply the landing page of the restaurant on resy.com. Go to resy, find the restaurant you want to book at
# and click it. This page will show times, desired seating such as "Bar" etc.,
# This is the URL you want to copy from the browser address bar and paste here.
venue_url = "https://resy.com/cities/atlanta-ga/venues/tiger-sun?date=2025-01-20&seats=2"  # Type: str